In [26]:
import tensorflow as tf
import numpy as np
import math

In [22]:
label=np.asarray([[0.,0. ,0.,0., 0., 0. ,0., 1., 0. ,0.],
                  [0.,0.,1.,0.,0.,0.,0.,0.,0.,0.]])
logitis=np.asarray([[-4.8788553e+02 ,-1.4091377e+03 ,-5.2255757e+03,1.4094987e+03, -1.7378435e+03 , 
                     1.8822108e+03 ,4.9372581e+01 , 4.1209521e+03, -1.7415996e+03 ,1.1880408e+03],
                    
                   [-1.0350179e+03,-1.2889645e+03,-5.3551914e+03,2.1222205e+03,-1.7806185e+03 , 
                    2.0163844e+03 , 1.0864736e+02 , 4.2028843e+03,-2.1118005e+03 , 1.7040602e+03]])

In [23]:
loss=tf.nn.softmax_cross_entropy_with_logits_v2(labels=label,logits=logitis)


In [53]:
tf_max=tf.reduce_max(logitis,axis=1)
tf_max=tf.reshape(tf_max,(2,1))
tf_max=tf.matmul(tf_max,tf.constant(value=1,shape=[1,10],dtype=tf.float64))

logitis=logitis-tf_max

logitis2=tf.reduce_logsumexp(logitis)

softmax_value=tf.nn.softmax(logitis)
clip_coftmax=tf.clip_by_value(softmax_value,1e-32,1.0)
loss2=-tf.reduce_sum(label*tf.log(tf.clip_by_value(tf.nn.softmax(logitis),1e-32,1.0)))

In [55]:
with tf.Session() as sess:
    print(sess.run(logitis2))
    print(sess.run(logitis))
    print(sess.run(tf_max))
    print(sess.run(softmax_value))
    print(sess.run(clip_coftmax))
    result,result2=sess.run([loss,loss2])
    print(result,result2)

0.6931471805599453
[[-4608.83763  -5530.0898   -9346.5278   -2711.4534   -5858.7956
  -2238.7413   -4071.579519     0.       -5862.5517   -2932.9113  ]
 [-5237.9022   -5491.8488   -9558.0757   -2080.6638   -5983.5028
  -2186.4999   -4094.23694      0.       -6314.6848   -2498.8241  ]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
[[1.e-32 1.e-32 1.e-32 1.e-32 1.e-32 1.e-32 1.e-32 1.e+00 1.e-32 1.e-32]
 [1.e-32 1.e-32 1.e-32 1.e-32 1.e-32 1.e-32 1.e-32 1.e+00 1.e-32 1.e-32]]
[   0.     9558.0757] 73.68272297580947


0.0